import type { Metadata } from "next";
import "@/app/globals.css";
import { languages } from "@/app/i18n/config";
import { Providers } from "./provider";
import {} from "mobx"

import Header from "@/components/header";
import Footer from "@/components/footer";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lng },
}: Readonly<{
  children: React.ReactNode;
  params: Record<string, string>;
}>) {
  return (
    <html lang={lng}>
      <body>
        <Providers>
          <div className="flex flex-col min-h-screen">
            <Header lng={lng}></Header>
            <div className="flex-1">{children}</div>
            <Footer></Footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
