import type { Metadata } from "next";
import "@/app/globals.css";
import { languages } from "@/app/i18n/config";
import { NextUIProviders } from "@/app/providers/nextUIProvider";
import { MobxProviders } from "@/app/providers/mobxProvider";

import Header from "@/components/header";
import Footer from "@/components/footer";

import styles from "./index.module.scss";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: "Mythos Ma",
  description: "Generated by Mythos Ma",
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Record<string, string>;
}>) {
  return (
    <html lang={params.lng}>
      <body>
        <MobxProviders>
          <NextUIProviders>
            <div
              className={[
                styles["page-background"],
                "p-[4%] h-[100vh] overflow-hidden",
              ].join(" ")}
            >
              <div className={[styles["main-card-background"]].join(" ")}>
                <div className={[styles["main-card-light"]].join(" ")} />
                <div
                  className={[
                    styles["main-card-container"],
                    "flex flex-col px-10",
                  ].join(" ")}
                >
                  <Header lng={params.lng}></Header>
                  <div className="flex-1">{children}</div>
                  <Footer></Footer>
                </div>
              </div>
            </div>
          </NextUIProviders>
        </MobxProviders>
      </body>
    </html>
  );
}
